# srcs/docker-compose.yml
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb        # mismo nombre que el servicio
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - USER_PASSWORD=${USER_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --socket=/run/mysqld/mysqld.sock --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  # placeholders para el resto (los completaremos luego) 
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443" # 8443 mapeado a 443 del contenedor para el local de 42
    volumes:
      - wordpress_data:/var/www/html
    networks: [inception]
    restart: always
    depends_on:
      wordpress:
        condition: service_started

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - USER_PASSWORD=${USER_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks: [inception]
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpico-bu/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpico-bu/data/wordpress
